# ── WHY FAISS WAS USED INITIALLY ──────────────────────────────────────────
# FAISS (Facebook AI Similarity Search) was our first vector search solution.
# It's extremely fast at finding similar vectors using cosine similarity via
# IndexFlatIP (Inner Product on normalized vectors). We built a custom
# persistence layer around it — saving the DataFrame (chunks + embeddings)
# as a .joblib file and the index as a .faiss file, then loading both back
# into a RAM dictionary (store={}) on startup.
#
# THE PROBLEM: Everything lived in RAM. Every document's embeddings were
# loaded into memory at startup and stayed there permanently. This works fine
# for 3-4 small PDFs during development, but doesn't scale — 50 large financial
# reports would exhaust memory. We also had to maintain our own brittle
# save/load/delete logic with no metadata filtering or querying capabilities.
# ──────────────────────────────────────────────────────────────────────────


# ── WHY CHROMADB REPLACED FAISS ───────────────────────────────────────────
# ChromaDB is a purpose-built vector database. Unlike FAISS which is just a
# search library requiring us to build everything around it, ChromaDB handles
# persistence, metadata storage, and similarity search natively as one system.
#
# KEY IMPROVEMENTS OVER FAISS:
# 1. Disk-based — collections are saved automatically, nothing lives in RAM
#    permanently. Documents are loaded on demand, not all at startup.
# 2. Metadata filtering — each chunk stores page_num and type alongside its
#    embedding, enabling future filtering like "search only table chunks" or
#    "search only pages 30-40".
# 3. No custom save/load code — ChromaDB manages its own persistence. No more
#    joblib.dump, faiss.write_index, or the store={} dictionary.
# 4. Scales cleanly — adding 100 documents doesn't increase startup RAM usage.
# 5. Foundation for multi-document querying — ChromaDB can query across
#    multiple collections, which FAISS required significant custom code for.
#
# NOTE: FAISS code is kept below as a reference and fallback during transition.
# Once ChromaDB is confirmed stable, the FAISS functions and store={} dict
# in main.py can be removed entirely.
# ──────────────────────────────────────────────────────────────────────────


import re#for finding patters in text, regular expressions
import ftfy#for fixing the erros in parsing the text from pdf due to encoding issues
import faiss#for efficient similarity search and clustering of dense vectors.organizes vectors intelligently so it doesn't have to check every single one
import joblib #for saving the embeddings generated by ollama
import numpy as np
import pandas as pd
import requests#for requsting Ollama for embeddings
import pdfplumber#for parsing PDF files
from itertools import groupby
from sklearn.preprocessing import normalize
import json
import os
import chromadb
from chromadb.config import Settings

OLLAMA_BASE = os.getenv("OLLAMA_BASE", "http://localhost:11434")
EMBED_MODEL = "embeddinggemma"
LLM_MODEL = "deepseek-r1"


# ─────────────────────────────────────────────
# PDF EXTRACTION
# ─────────────────────────────────────────────

def extract_pdf(file_path):
    print('Extracting PDF:', file_path)
    pages = []
    with pdfplumber.open(file_path) as pdf:
        for i, page in enumerate(pdf.pages):
            tables = page.find_tables()

            # 1. Clean text (exclude table bounding boxes)
            non_table_page = page
            for table in tables:
                bbox = table.bbox
                non_table_page = non_table_page.filter(
                    lambda obj, bbox=bbox: not (
                        obj["x0"] >= bbox[0] and obj["x1"] <= bbox[2] and
                        obj["top"] >= bbox[1] and obj["bottom"] <= bbox[3]
                    )
                )
            text = ftfy.fix_text(non_table_page.extract_text() or "")

            # 2. Extract tables with context
            tables_list = []
            full_text = ftfy.fix_text(page.extract_text() or "")
            lines = full_text.split("\n")

            for table in tables:
                table_block = ""
                for row in table.extract():
                    clean_row = [cell or "" for cell in row]
                    row_text = " | ".join(clean_row).strip()
                    if "|" not in row_text:
                        continue
                    table_block += row_text + "\n"

                if not table_block.strip():
                    continue

                # Get 2 lines of context above table using bbox
                table_top = table.bbox[1]
                above_lines = []
                for obj in page.chars:
                    if obj["bottom"] < table_top:
                        above_lines.append((obj["bottom"], obj["text"]))

                above_lines.sort(key=lambda x: x[0])
                grouped = groupby(above_lines, key=lambda x: round(x[0], 1))
                text_lines = []
                for _, chars in grouped:
                    line_text = "".join(c[1] for c in chars).strip()
                    if line_text:
                        text_lines.append(line_text)

                context_lines = [l for l in text_lines if l.strip()][-6:]
                header_text = "\n".join(context_lines)

                tables_list.append({
                    "context": header_text,
                    "block": table_block,
                    "text_lines": text_lines
                })

            pages.append({
                "text": text,
                "tables": tables_list,
                "page_num": i + 1
            })

    return pages


# ─────────────────────────────────────────────
# TABLE NARRATION
# ─────────────────────────────────────────────

def narrate_table(tables_list, page_num):
    print('narrate_table called for page: ',page_num,' Num of tables: ',len(tables_list))
    if not tables_list:
        return []

    all_chunks = []
    for table in tables_list:
        if not table["block"].strip():
            continue

        prompt = f"""You are a financial analyst. Convert this single financial table into clear sentences.
The table context/heading tells you what the table is about.
IMPORTANT: If the values are percentages, state them as percentages NOT dollar amounts.
If the values are dollar amounts, state them in millions of dollars.

Table context/heading: {table["context"]}

Table data:
{table["block"]}

Write only the sentences, nothing else."""

        r = requests.post(f"{OLLAMA_BASE}/api/generate", json={
            "model": LLM_MODEL,
            "prompt": prompt,
            "stream": False
        })

        narrative = r.json().get("response", "").strip()
        narrative = re.sub(r"<think>.*?</think>", "", narrative, flags=re.DOTALL).strip()

        if not narrative:
            continue

        sentences = re.split(r"(?<=[.!?])\s+", narrative)
        buffer = ""
        for sentence in sentences:
            if len((buffer + " " + sentence).split()) < 150:
                buffer += " " + sentence
            else:
                if buffer.strip():
                    all_chunks.append({
                        "text": f"{buffer.strip()}\n[Page {page_num}]",
                        "page_num": page_num,
                        "type": "table"
                    })
                buffer = sentence

        if buffer.strip():
            all_chunks.append({
                "text": f"{buffer.strip()}\n[Page {page_num}]",
                "page_num": page_num,
                "type": "table"
            })

    return all_chunks


# ─────────────────────────────────────────────
# CHUNKING
# ─────────────────────────────────────────────

def chunk_text(pages, chunk_size=200, overlap=50,  on_page=None):
    print('chunk_text called. creating chunks. Num of pages: ',len(pages))
    chunks = []
    for page in pages:

        if on_page:
            on_page(page["page_num"], len(pages))

        paragraphs = re.split(r"\n\s*\n", page["text"])
        for para in paragraphs:
            words = para.split()
            if len(words) < 8:
                continue
            if para.lower().strip() in ["table of contents"]:
                continue
            if len(set(words)) < 3:
                continue

            start = 0
            while start < len(words):
                chunk_words = words[start:start + chunk_size]
                if len(chunk_words) < 20 and start > 0:
                    break
                chunks.append({
                    "text": " ".join(chunk_words),
                    "page_num": page["page_num"],
                    "type": "text"
                })
                start += chunk_size - overlap

        table_chunks = narrate_table(page.get("tables", []), page["page_num"])
        chunks.extend(table_chunks)
      
    print('Chunks Created: ',len(chunks))
    return chunks


# ─────────────────────────────────────────────
# EMBEDDINGS
# ─────────────────────────────────────────────

def create_embedding(text_list):
    r = requests.post(f"{OLLAMA_BASE}/api/embed", json={
        "model": EMBED_MODEL,
        "input": text_list
    })
    return r.json()["embeddings"]


def batch_embeddings(texts, batch_size=50,totalSize=None):
    all_embeddings = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i:i + batch_size]
        print(f"Embedding batch {i} to {i+len(batch)} Total({totalSize})")
        emb = create_embedding(batch)
        all_embeddings.extend(emb)
    return all_embeddings


# ─────────────────────────────────────────────
# RANKING
# ─────────────────────────────────────────────

def apply_better_ranking(results, question):
    print('applying better ranking to the results based on keyword matching and table type')
    def keyword_score(text):
        words = re.findall(r"\w+", question.lower())
                # return sum(word in text.lower() for word in words if len(word) > 2)
        #pythonic way to write the below.
        count = 0

        for word in words:              # 1. The Loop
            if len(word) > 2:           # 2. The Filter
                if word in text.lower(): # 3. The Action
                    count += 1          # 4. The Container (sum)
        return count;

    results["keyword_score"] = results["text"].apply(keyword_score)
    if results["keyword_score"].max() > 0:
        results["keyword_score"] = results["keyword_score"] / results["keyword_score"].max()

    results["type_score"] = (results["type"] == "table") * 0.02
    results["final_score"] = (
        results["score"] +
        0.2 * results["keyword_score"] +
        results["type_score"]
    )
    return results.sort_values(by="final_score", ascending=False)


def build_context(question, results, top_k=5):
    context = ""
    results = results.sort_values(by="final_score", ascending=False)
    for _, row in results.head(top_k).iterrows():
        context += f"[Page {row['page_num']} | Type: {row['type']}]\n"
        context += row["text"] + "\n\n"
    return context


# ─────────────────────────────────────────────
# LLM
# ─────────────────────────────────────────────


def ask_llm_stream(question, context):
    prompt = f"""You are a helpful assistant that answers questions about company financial documents.
Answer the question using ONLY the context provided below.
If the answer is not found in the context, say "I could not find this in the document."

Context:
{context}

Question: {question}

Answer clearly and concisely."""

    r = requests.post(f"{OLLAMA_BASE}/api/generate", json={
        "model": LLM_MODEL,
        "prompt": prompt,
        "stream": True   # ← only difference from ask_llm
    }, stream=True)

    think_buffer = ""
    in_think = False

    for line in r.iter_lines():
        if not line:
            continue
        try:
            chunk = json.loads(line)
        except:
            continue

        token = chunk.get("response", "")

        # strip <think> tags from deepseek on the fly
        think_buffer += token
        while True:
            if in_think:
                end = think_buffer.find("</think>")
                if end != -1:
                    think_buffer = think_buffer[end + 8:]
                    in_think = False
                else:
                    think_buffer = ""
                    break
            else:
                start = think_buffer.find("<think>")
                if start != -1:
                    yield think_buffer[:start]
                    think_buffer = think_buffer[start + 7:]
                    in_think = True
                else:
                    yield think_buffer
                    think_buffer = ""
                    break

def ask_llm(question, context):
    prompt = f"""You are a helpful assistant that answers questions about company financial documents.
Answer the question using ONLY the context provided below.
If the answer is not found in the context, say "I could not find this in the document."

Context:
{context}

Question: {question}

Answer clearly and concisely."""

    r = requests.post(f"{OLLAMA_BASE}/api/generate", json={
        "model": LLM_MODEL,
        "prompt": prompt,
        "stream": False
    })
    raw = r.json()["response"]
    # strip deepseek think tags
    return re.sub(r"<think>.*?</think>", "", raw, flags=re.DOTALL).strip()



# ─────────────────────────────────────────────
# CHROMADB
# ─────────────────────────────────────────────
#ChromaDB is a purpose-built vector database. It's designed specifically to store embeddings and search them efficiently

def get_chroma_client(persist_dir="chroma_store"):
    return chromadb.PersistentClient(path=persist_dir)


def build_chroma_collection(doc_id, chunks, embeddings, persist_dir="chroma_store"):
    client = get_chroma_client(persist_dir)

    # delete existing collection for this doc if re-ingesting
    try:
        client.delete_collection(name=doc_id)
    except:
        pass
    
    #Collection = table for ONE document. Each document gets its own collection. Collections have metadata and support similarity search.
    collection = client.create_collection(
        name=doc_id,
        metadata={"hnsw:space": "cosine"}  # use cosine similarity
    )

    # ChromaDB expects lists, not numpy arrays
    ids = [str(i) for i in range(len(chunks))]
    docs = [c["text"] for c in chunks]
    embeds = [e if isinstance(e, list) else e.tolist() for e in embeddings]
    metadatas = []

    for i, c in enumerate(chunks):
        metadata = {
            "page_num": int(c["page_num"]),
            "type": c["type"],
            "chunk_id": int(i)
        }
        metadatas.append(metadata)

    collection.add(
        ids=ids,
        embeddings=embeds,
        documents=docs,
        metadatas=metadatas
    )

    print(f"ChromaDB collection '{doc_id}' built with {len(chunks)} chunks")
    return collection


def search_chroma(query, doc_id, top_k=10, persist_dir="chroma_store"):
    print(f"\nChromaDB Query: {query}\n")
    client = get_chroma_client(persist_dir)
    collection = client.get_collection(name=doc_id)

    # embed the query
    query_embedding = create_embedding([query])[0]

    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=top_k,
        include=["documents", "metadatas", "distances"]
    )

    # convert to DataFrame to keep rest of pipeline unchanged
    docs = results["documents"][0]
    metas = results["metadatas"][0]
    distances = results["distances"][0]

    df = pd.DataFrame({
        "text": docs,
        "page_num": [m["page_num"] for m in metas],
        "type": [m["type"] for m in metas],
        # chroma cosine distance: 0=identical, 2=opposite → convert to similarity score
        "score": [1 - d for d in distances]
    })

    return df.sort_values(by="score", ascending=False)

def delete_chroma_collection(doc_id, persist_dir="chroma_store"):
    client = get_chroma_client(persist_dir)
    client.delete_collection(name=doc_id)
    print(f"ChromaDB collection '{doc_id}' deleted")
    
def list_chroma_collections(persist_dir="chroma_store"):
    client = get_chroma_client(persist_dir)
    return [c.name for c in client.list_collections()]

def save_suggestions_with_embeddings(doc_id, suggestions, persist_dir="chroma_store"):
    client = get_chroma_client()
    collection = client.get_collection(name=doc_id)
    
    # embed each question locally using ollama
    question_embeddings = []
    for q in suggestions:
        emb = create_embedding([q])[0]
        question_embeddings.append(emb)
    
    # store as JSON: list of {question, embedding}
    data = [
        {"question": q, "embedding": e}
        for q, e in zip(suggestions, question_embeddings)
    ]
    
    collection.upsert(
        ids=["__suggestions__"],
        embeddings=[[0.0] * 768],
        documents=[json.dumps(data)],  # now stores embeddings too
        metadatas=[{"type": "suggestions", "page_num": 0, "chunk_id": -1}]
    )
    print(f"Saved {len(suggestions)} suggestions with embeddings for '{doc_id}'")

def load_suggestions_with_embeddings(doc_id):
    try:
        print(f"Loading suggestions with embeddings for '{doc_id}'")
        client = get_chroma_client()
        collection = client.get_collection(name=doc_id)
        result = collection.get(ids=["__suggestions__"])
        if result["documents"]:
            return json.loads(result["documents"][0])
            # returns: [{"question": "...", "embedding": [...]}, ...]
    except:
        pass
    return []

def search_chroma_with_embedding(query_embedding, doc_id, top_k=10):
    client = get_chroma_client()
    collection = client.get_collection(name=doc_id)
    
    results = collection.query(
        query_embeddings=[query_embedding],  # ← use stored embedding directly
        n_results=top_k,
        include=["documents", "metadatas", "distances"]
    )
    
    docs = results["documents"][0]
    metas = results["metadatas"][0]
    distances = results["distances"][0]
    
    df = pd.DataFrame({
        "text": docs,
        "page_num": [m["page_num"] for m in metas],
        "type": [m["type"] for m in metas],
        "score": [1 - d for d in distances]
    })
    return df.sort_values(by="score", ascending=False)

def generate_question_for_chunk(chunk_text):
    prompt = f"""You are analyzing a financial document. Based on the following text, generate exactly ONE specific and interesting question that can be answered from this content.

The question can be a little generic but should be answerable from the content. Avoid questions that are too specific or require information not contained in the text.
Return ONLY the question, nothing else. No numbering, no explanation.

Generate exactly ONE question (max 7 words).

Strict rules:
- No prefix
- No explanation
- No extra text
- Only the question

Text:
{chunk_text[:800]}

Question:"""

    r = requests.post(f"{OLLAMA_BASE}/api/generate", json={
        "model": LLM_MODEL,
        "prompt": prompt,
        "stream": False
    })
    raw = r.json().get("response", "").strip()
    # strip deepseek think tags
    raw = re.sub(r"<think>.*?</think>", "", raw, flags=re.DOTALL).strip()
    # clean up — remove quotes if LLM wraps in them
    raw = raw.strip('"').strip("'").strip()
    return raw if raw else None